name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'ble-mqtt-${{github.ref_name}}.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ble-mqtt-${{github.ref_name}}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
